### ISSUE TITLE
Cant stream Netflix in HD

### ISSUE THREAD

**Issue by neziak24** [ValdikSS/GoodbyeDPI#173]
Does goodbyedpi effect netflix stream quality? Because im unable to reach HD although i have the ultra HD plan and im stuck in 480p max (and sometimes cant reach 480p). Thanks in advance!

**Comment by ValdikSS** [comment]
GoodbyeDPI should not affect stream quality, but due to its anti-DPI design, it may interfere with provider's DPI systems, which may also be used for good, for example to re-route Netflix traffic over better network route.
Can't say for sure on that. But generally GoodbyeDPI does not cause any noticeable speed decrease.
