### ISSUE TITLE
Not Working with Windows 10 version 2004 (May Update)

### ISSUE THREAD

**Issue by tamacroft** [ValdikSS/GoodbyeDPI#184]
Before update (windows 10 version 1909) this is work, but after upgrade version of windows 10 GoodbyeDPI didn't work.  Please dont ask me to downgrade windows 10 version 😁

**Comment by r4sas** [comment]
Telepaths on vacation. Logs?

**Comment by ValdikSS** [comment]
A friend of mine uses the software on build 2004 without any issues. What exactly doesn't work for you?

**Comment by tamacroft** [comment]
in my country, netflix is blocked by ISP, i can't use netflix app in build 2004

[https://photos.app.goo.gl/jqSUTRGiyWvePoEPA](url)

**Comment by ValdikSS** [comment]
My PC failed to update to 2004 and reverted back to 1909. I can't test it. As far as I know, 2004 update is considered unstable or faulty, I would recommend reverting back to 1909 until further updates.

**Comment by Mxkkxa** [comment]
I am on build 2004 and works fine for me.

**Comment by ValdikSS** [comment]
I've been contacted by another person from Russia who assumed the software stopped working after 2004 update. As was found later, it wasn't true, it had no connection with the update.
@tamacroft, could you provide more details of the issue? What exactly stopped working after 1909→2004 update? Are you absolutely sure this happened due to the update, and not other configuration differences?

**Comment by Liiion911** [comment]
Yes, after update windows to 2004 my provider (ertelecom) started blocking sites again.
example site: seasonvar.ru https://yadi.sk/i/wnrn2C3VER631w
what information you need for fix?

**Comment by Liiion911** [comment]
Tested on Green Tunnel and PowerTunnel - same problem.

**Comment by Erquint** [comment]
Latest set of Windows 10 feature updates and their hotfixes are messing with hardware drivers, among which embedded Realtek Ethernet drivers are especially affected along with Realtek and other manufacturers' audio drivers and (I think) there's also something going on with video drivers. MS is reviving A2DP support, which is probably related. You can find many annoyed user reports online.

1909, for a personal example, crippled my embedded soundcard, forcing me to use generic MS drivers for it, which lack the manufacturer featureset. GoodbyeDPI still worked.

About yesterday I updated to 20H2 and today I noticed GoodbyeDPI not working anymore.
I contacted my ISP (RT) and their representative was eager to assure me their blocking tech didn't change. I may have not been the first to ask.
I'm still troubleshooting it on my end since I was running my machine RAM-deprived for weeks lately, but I wouldn't at all be surprised if this yet another Windows 10 driver conflict.

Мелкософт посл. время не желает решать конфликты драйверов на своей стороне, ожидая, что их пофиксит вторая сторона. Такие дела…

**Comment by ValdikSS** [comment]
I still have no strong confirmation that 2004 update is somehow involved in this behaviour.
@Liiion911, @Erquint, please collect Wireshark dump and provide it here or by my email iam@valdikss.org.ru.
The manual: [Как сделать дамп трафика в Wireshark](https://github.com/ValdikSS/GoodbyeDPI/wiki/Как-сделать-дамп-трафика-в-Wireshark) / [How to make traffic dump with Wireshark](https://github.com/ValdikSS/GoodbyeDPI/wiki/How-to-make-traffic-dump-with-Wireshark)

**Comment by ValdikSS** [comment]
Works fine with current Windows builds.
