### ISSUE TITLE
Add support for OpenWrt

### ISSUE THREAD

**Issue by yesrab** [ValdikSS/GoodbyeDPI#293]
### Describe your feature / Опишите ваше предложение

Adding support for Openwrt can go a long way to bypass censorship over various devices connected to a single router

**Comment by r4sas** [comment]
RTFM README!

**Comment by rdavydov** [comment]
GoodbyeDPI is Windows-only.
OpenWRT is based on Linux, not Windows.
You can check https://github.com/ValdikSS/GoodbyeDPI#similar-projects for Linux.

**Comment by 7gxycn08** [comment]
You can Just run a windows vm running Goodbyedpi and install a proxy server such as Privoxy then send your clients to the proxy and all the traffic will be filtered by Goodbyedpi.

**Comment by omercerci** [comment]
If you share with us what the program does as open source or share a documentation of what it does from the beginning to the end so that it can be done as an OpenWRT plugin, a new plugin can be written about this topic. With Zapret, you can simulate exactly what this program does and write a more automated GoodbyDPI plugin.
