### ISSUE TITLE
ERR_SSL_PROTOCOL_ERROR for not banned/cencored site.

### ISSUE THREAD

**Issue by adeep** [ValdikSS/GoodbyeDPI#340]
### Operating system / операционная система

Windows 10 2H22

### Running as service / Запуск программы как сервис

I installed it as a service / Установил как сервис Windows

### Describe the bug / Опишите ошибку программы

Thanks for this application. It's unblock all ISP blocked site in my country.
But my problem is normal site (not blocked.) Like microsoft.com.  It gives ERR_SSL_PROTOCOL_ERROR and ERR_CONNECTION_RESET error. Sites open with no problem when Goodbyedpi disabled.
I don't know how to fix it or where to look it. I enabled SecureDNS (Cloudflare ).

![chrome_4HRK2SmA0V](https://github.com/ValdikSS/GoodbyeDPI/assets/374042/87283277-12b1-4fab-81d1-2a7bdceafdb3)

**Comment by bogdeskaa** [comment]
Same problem here. The only way to open some pages when Goodbyedpi is running is to refresh them 10+ times.

**Comment by ValdikSS** [comment]
Most probably either the requested websites don't support fragmented TLS packets, or your ISP explicitly drop them due to inability to analyze them.

Anything definitive could be told only by analyzing traffic dump.
https://github.com/ValdikSS/GoodbyeDPI/wiki/How-to-make-traffic-dump-with-Wireshark

This is unlikely to be a software bug, reopen the issue if you believe otherwise.
