### ISSUE TITLE
Virus?

### ISSUE THREAD

**Issue by qo4on** [ValdikSS/GoodbyeDPI#376]
### Operating system / операционная система

Windows 10 20H2

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

Why does virustotal.com find so many viruses here?
https://www.virustotal.com/gui/file/00a2f8b99cd817f8c7fc4c449033015f039d18af213de78cb66bf202277c0628
![image](https://github.com/user-attachments/assets/e2c8acaf-3f78-4371-9733-49bf2602ed88)

**Comment by awgv** [comment]
@qo4on Information on VirusTotal is not a guarantee—you end up with malicious software being flagged as clean and vice versa. In fact, it’s pretty trivial to fool. The reason VirusTotal false-flagged GoodbyeDPI specifically is because it uses WinDivert (hinted at on your screenshot), which is an open-source packet manipulation driver that can absolutely be used for malicious purposes (note the ESET-NOD32 comment), even though it’s not malicious itself. It does make some sense to assume something that can intercept packets to be malicious, but then again, a lot of legitimate software manipulates packets, as well as uses WinDivert.

What’s important to understand is that GoodbyeDPI is pretty old at this point (as far as I can remember, it will be 10 years in 2027) and has tens of thousands technically inclined users across the globe that run it as a daily driver—if it had malicious code, it would’ve been found, and this repository would’ve been hidden by GitHub, which also does at least a good enough job to prevent malware on the platform.

Not to mention the fact that the maintainer is well-known and reliable, but you’ll have to trust me on that.

**Comment by ValdikSS** [comment]
That's false positive for WinDivert driver. If you want it removed, you need to contact these antivirus vendors and report for false positive.

**Comment by Kfizzrixs** [comment]
Влад ты ебаный хуесос, это майнер

**Comment by Kfizzrixs** [comment]
Тварь ебаная чтобы вся твоя семья сдохла от ебаного вича в муках

**Comment by Kfizzrixs** [comment]
Анимешный пидорас

**Comment by Kfizzrixs** [comment]
В очко себе этот палец засунь тварь ебаная со своим майнером
