### ISSUE TITLE
Youtube looses seek bar

### ISSUE THREAD

**Issue by datsideofthemoon** [ValdikSS/GoodbyeDPI#398]
### Operating system / операционная система

10 22H2

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

Youtube seek bar stops working, time tooltip says "NaN:NaN". Video plays normally from start.
Tried turning off Kyber, nothing changes. Tried both browsers, same.

**Comment by ValdikSS** [comment]
Yeah.

**Comment by datsideofthemoon** [comment]
What you mean by "yeah"? Can you help with problem?

**Comment by ValdikSS** [comment]
This is not a software bug and should not be reported here. You didn't read the text before creating the issue.

**Comment by datsideofthemoon** [comment]
I thought it could be packet cutting issue. If you SURE not, even without looking, than okay..

**Comment by ValdikSS** [comment]
I'm not sure, but most likely it isn't. This is a very common issue due to how traffic mangling works - sometimes it breaks the website. Default configuration of GoodbyeDPI aims to work on most ISP in most conditions, but not all of them, thus require tuning to work in your case.

If in doubt, you can [create a traffic capture](https://github.com/ValdikSS/GoodbyeDPI/wiki/How-to-make-traffic-dump-with-Wireshark).

**Comment by datsideofthemoon** [comment]
Okay did some more testing, problem persists after closing program. Reload page 3 times out of 10 seek starts working back. Looks like some temporal bug on yt or dunno
